### ISSUE TITLE
Internet Health Report 2018 - First content draft for your review

### ISSUE THREAD

**Issue by kaodro** [MozillaFoundation/mozfellows-2017#1]
* **I'm submitting a ... **
  - [X] contribution request
  - [ ] interview request
  - [ ] support request
  - [ ] event invite
  - [ ] opportunity for participation
  - [ ] bug report about this repo
  - [ ] other (highly relevant) thing

* **Which fellows are you directing this ask toward (Open Web, Science, Media, All...)**
We are directing our ask at Open Web, Science, Media and Tech Policy fellows.

* **Describe your request.**
Dear Fellows,

My name is Kasia and I work with Solana on the Internet Health Report. As promised, today we are sharing with you the first draft of the Report's content. Thank you in advance for taking time to review it - we really appreciate your help and involvement in the Report.

To make it more manageable, we created a common folder and divided the content into
- 5 issue pages documents. Each of the documents contains blocks that belong to the page. Some articles are still forthcoming and marked as such. We also included data visualization "headlines" to give you a more complete picture of what is still coming.
- 1 document for homepage & introductions copy
- A supporting document with content headlines overview (our working doc, in progress)

I granted you permission to access the folder. You can find it here:  https://drive.google.com/open?id=1AKerAPY4fgSoUfRiGlSppvc48-Ug91Gy

**How to review?**
We thank you in advance for reviewing individual articles that match your expertise, as well as the issue pages as a whole, looking over the headlines and **identifying if there are any topics missing** (at the **bottom of the page** you have space to enter them and the issue documents are set to a "suggesting edits" mode). You can also **leave comments everywhere you see fit** using the comment function. If you have **general feedback, just send it over to Solana and me via Email.**
We very much welcome comments on specific issue pages: what's good, what's bad, what's crazy, what you loved and what you hated.

Please note that these are "living documents" in progress and it is likely they will be changing a bit during the review process and definitely after. **If you see a piece that is still open and you would be up for writing it, just let us know.**

* **What is the motivation / use case for this request of the fellows?**
We would like to engage fellows into the creation of the upcomign Internet Health Report and benefit from their expertise and ideas. We invite them to review the early draft of the Report, as well as write open articles and suggest topics/perspectives that are missing in their opinion.

* **Please tell us about your deadline for this request:**
We would like to ask the fellows to be done with the review by December 6.

* **Other information** (e.g. detailed explanation, related issues, links for us to have context, eg. urls, slack posts, doc links, etc)

Context related to the structure of the upcoming Report:

As in the[ prototype](https://internethealthreport.org/v01/), we will structure the 2018 version of the report along five “issues”: openness, privacy & security, decentralization, digital inclusion and web literacy. 

The current design prototype for 2018 is linked from the documents available for ou for content review.

All content will be divided into approximately 100 “blocks” (20 per issue) that are short, standalone, texts (fact analysis or stories featuring people or/and projects) and/or data and visuals, that can also be shared and embedded elsewhere. Blocks will range from 150-600 words. Users will be able to comment on and react to each block. 

As something new, we will be highlighting one “Trending topic” for each of the five issues, and exploring its subject matter in more depth with different types of content blocks.

We will also have the following sub-pages:

Introduction -- will explain what the Internet Health Report is, contrast and compare findings of the previous year, and highlight notable trends and changes. 
Explore -- will allow users to search and mix/match all blocks, using different keywords and topics.
Participate -- will provide an overview of what actions users can take, offer a way to contact us, and gather all comments/interactivity from throughout the Report.

Thank you for your help!

**Comment by chartgerink** [comment]
@kaodro on my schedule! Thanks for the invite 👏

**Comment by kaodro** [comment]
Thank you to all who participated in the first round of reviews. Your feedback is incredibly valuable and we will be working on incorporating into the second draft soon after All Hands. We will be in touch with all who offered their help. Thank you again for your time. Fellows power!
