### ISSUE TITLE
Fellows: submit profiles and project info

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mozfellows-2017#3]
For All fellows

  - [x] contribution request
  - [x] opportunity for participation

### Description

Join Pulse. Create a profile, submit an entry. Build a practice of gathering and posting resources, big and small. 

### Use case

For Mozilla, Pulse provides a single, standard tool to track the people and initiatives contributing toward a healthy internet. 

For Fellows, this space provides an opportunity to 1) document your contributions to the movement, 2) find and be found to initiate collaborations, 3) queue up your work for inclusion in our various channels of communication for promotion, 4) be identified as we track internet health indicators and drivers of the movement. 

### Deadline

Prior to Fellows work week. We can use time at work week to review and follow-up. New fellows pages on foundation site will point toward these profiles and projects.  

### Start here

1. Go to https://mozillapulse.org/
 2. Signup
 3. Add [your profile](https://mozillapulse.org/myprofile)
 4. Browse your interests (e.g. [/tags/iot](https://www.mozillapulse.org/tags/iot)) or issue (e.g. [/issues/digital-inclusion](https://www.mozillapulse.org/issues/digital-inclusion))
 5. Post your projects 
    - Posts can be big initiatives and small resources (even a google doc template or best practice)
    - Projects can be done and polished or a work-in-progress
    - If possible, include info on how people can get involved (e.g. [/help/take action](https://www.mozillapulse.org/help/Take%20Action))

**Comment by chartgerink** [comment]
@xmatthewx thanks for the invite! I just added a project

https://www.mozillapulse.org/entry/572

While doing this I noticed it is not possible to save drafts? It would really help to be able to do that, because I have a few projects I'd like to get ready for Pulse but I feel I need to work on them a bit more before actually putting them on there.

**Comment by xmatthewx** [comment]
Thanks @chartgerink. Sorry for the slow reply. Holidaze! 

We have other features we're developing right now, but I will add Drafts to our list of potential future features. No promises, but it is possible. Also... I think that a work-in-progress is appropriate on Pulse. You can post again when a project reaches a new milestone. Another solution besides drafts might be a way to flag that a thing is a work in progress, rough around the edges. 

Also... I love your diagram. My brother-in-law is a physicist and looks a lot like Researcher B.
